/* ============================================================
   GlobalDS iconography — exact audited Figma component inventory
   Source: Atoms - RIB / Icons (KlcvhcZPwn1c9BXBY2k6rl, node 92:6201)
   Generated from Figma component metadata and exported assets.
   ============================================================ */

const GlobalDSIconography = {
  "meta": {
    "fileKey": "KlcvhcZPwn1c9BXBY2k6rl",
    "nodeId": "92:6201",
    "source": "Atoms - RIB / Icons",
    "total": 283
  },
  "counts": {
    "general": {
      "filled": 112,
      "line": 32,
      "total": 144
    },
    "product": {
      "line": 27,
      "filled": 35,
      "special": 8,
      "total": 70
    },
    "special": {
      "special": 51,
      "total": 51
    },
    "sideNav": {
      "outlined": 9,
      "filled": 9,
      "total": 18
    }
  },
  "icons": [
    {
      "id": "235:113",
      "name": "Curated",
      "sourceName": "Filled/Curated",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/curated--filled--235-113.svg"
    },
    {
      "id": "235:114",
      "name": "Graph",
      "sourceName": "Filled/Graph",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/graph--filled--235-114.png"
    },
    {
      "id": "237:437",
      "name": "Calendar",
      "sourceName": "Filled/Calendar",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/calendar--filled--237-437.svg"
    },
    {
      "id": "237:438",
      "name": "Calendar-2",
      "sourceName": "Filled/Calendar-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/calendar-2--filled--237-438.svg"
    },
    {
      "id": "237:439",
      "name": "Edit",
      "sourceName": "Filled/Edit",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/edit--filled--237-439.svg"
    },
    {
      "id": "237:440",
      "name": "Star",
      "sourceName": "Filled/Star",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/star--filled--237-440.svg"
    },
    {
      "id": "237:441",
      "name": "Call",
      "sourceName": "Filled/Call",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/call--filled--237-441.png"
    },
    {
      "id": "237:442",
      "name": "Information",
      "sourceName": "Filled/Information",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/information--filled--237-442.svg"
    },
    {
      "id": "237:443",
      "name": "Radio button-on",
      "sourceName": "Filled/Radio button-on",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/radio-button-on--filled--237-443.svg"
    },
    {
      "id": "237:444",
      "name": "Radio button-off",
      "sourceName": "Filled/Radio button-off",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/radio-button-off--filled--237-444.svg"
    },
    {
      "id": "237:445",
      "name": "Checkbox-unchecked",
      "sourceName": "Filled/Checkbox-unchecked",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/checkbox-unchecked--filled--237-445.svg"
    },
    {
      "id": "237:446",
      "name": "Check box-checked",
      "sourceName": "Filled/Check box-checked",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/check-box-checked--filled--237-446.svg"
    },
    {
      "id": "237:447",
      "name": "Alert",
      "sourceName": "Filled/Alert",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/alert--filled--237-447.svg"
    },
    {
      "id": "237:448",
      "name": "Home",
      "sourceName": "Filled/Home",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/home--filled--237-448.svg"
    },
    {
      "id": "237:449",
      "name": "People",
      "sourceName": "Filled/People",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/people--filled--237-449.svg"
    },
    {
      "id": "237:450",
      "name": "Done",
      "sourceName": "Filled/Done",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/done--filled--237-450.svg"
    },
    {
      "id": "237:451",
      "name": "Error",
      "sourceName": "Filled/Error",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/error--filled--237-451.svg"
    },
    {
      "id": "237:452",
      "name": "Expand",
      "sourceName": "Filled/Expand",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/expand--filled--237-452.svg"
    },
    {
      "id": "237:453",
      "name": "Collapse",
      "sourceName": "Filled/Collapse",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/collapse--filled--237-453.svg"
    },
    {
      "id": "237:454",
      "name": "Download",
      "sourceName": "Filled/Download",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/download--filled--237-454.svg"
    },
    {
      "id": "237:455",
      "name": "Notebook",
      "sourceName": "Filled/Notebook",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/notebook--filled--237-455.png"
    },
    {
      "id": "237:456",
      "name": "Glitter",
      "sourceName": "Filled/Glitter",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/glitter--filled--237-456.svg"
    },
    {
      "id": "237:559",
      "name": "Bolt-1",
      "sourceName": "Filled/Bolt-1",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/bolt-1--filled--237-559.svg"
    },
    {
      "id": "237:560",
      "name": "Bank",
      "sourceName": "Filled/Bank",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/bank--filled--237-560.svg"
    },
    {
      "id": "237:561",
      "name": "Bulb-1",
      "sourceName": "Filled/Bulb-1",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/bulb-1--filled--237-561.svg"
    },
    {
      "id": "237:562",
      "name": "Bulb-2",
      "sourceName": "Filled/Bulb-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/bulb-2--filled--237-562.png"
    },
    {
      "id": "243:16",
      "name": "Person",
      "sourceName": "Filled/Person",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/person--filled--243-16.svg"
    },
    {
      "id": "324:111",
      "name": "Bolt",
      "sourceName": "Filled/Bolt",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/bolt--filled--324-111.png"
    },
    {
      "id": "324:129",
      "name": "Money-1",
      "sourceName": "Filled/Money-1",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money-1--filled--324-129.svg"
    },
    {
      "id": "324:139",
      "name": "Process-1",
      "sourceName": "Filled/Process-1",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/process-1--filled--324-139.svg"
    },
    {
      "id": "324:147",
      "name": "Process-2",
      "sourceName": "Filled/Process-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/process-2--filled--324-147.svg"
    },
    {
      "id": "324:151",
      "name": "Call",
      "sourceName": "Filled/Call",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/call--filled--324-151.svg"
    },
    {
      "id": "352:226",
      "name": "Money-2",
      "sourceName": "Filled/Money-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money-2--filled--352-226.svg"
    },
    {
      "id": "354:232",
      "name": "Piechart",
      "sourceName": "Filled/Piechart",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/piechart--filled--354-232.svg"
    },
    {
      "id": "355:246",
      "name": "Piechart-2",
      "sourceName": "Filled/Piechart-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/piechart-2--filled--355-246.svg"
    },
    {
      "id": "519:73",
      "name": "Lock",
      "sourceName": "Filled/Lock",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/lock--filled--519-73.svg"
    },
    {
      "id": "519:74",
      "name": "List",
      "sourceName": "Filled/List",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/list--filled--519-74.png"
    },
    {
      "id": "519:75",
      "name": "Umbrella",
      "sourceName": "Filled/Umbrella",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/umbrella--filled--519-75.svg"
    },
    {
      "id": "519:84",
      "name": "Leaf",
      "sourceName": "Filled/Leaf",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/leaf--filled--519-84.svg"
    },
    {
      "id": "548:237",
      "name": "Shield-1",
      "sourceName": "Filled/Shield-1",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/shield-1--filled--548-237.svg"
    },
    {
      "id": "549:241",
      "name": "Shield-2",
      "sourceName": "Filled/Shield-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/shield-2--filled--549-241.svg"
    },
    {
      "id": "549:255",
      "name": "Credit card",
      "sourceName": "Filled/Credit card",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/credit-card--filled--549-255.svg"
    },
    {
      "id": "1169:34",
      "name": "Document 3",
      "sourceName": "Filled/Document 3",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/document-3--filled--1169-34.svg"
    },
    {
      "id": "551:291",
      "name": "Money-3",
      "sourceName": "Filled/Money-3",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money-3--filled--551-291.svg"
    },
    {
      "id": "569:322",
      "name": "Government",
      "sourceName": "Filled/Government",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/government--filled--569-322.svg"
    },
    {
      "id": "570:329",
      "name": "Nominee",
      "sourceName": "Filled/Nominee",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/nominee--filled--570-329.svg"
    },
    {
      "id": "571:335",
      "name": "Document-1",
      "sourceName": "Filled/Document-1",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/document-1--filled--571-335.svg"
    },
    {
      "id": "574:31",
      "name": "Key-1",
      "sourceName": "Filled/Key-1",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/key-1--filled--574-31.svg"
    },
    {
      "id": "574:41",
      "name": "Car-2",
      "sourceName": "Filled/Car-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/car-2--filled--574-41.svg"
    },
    {
      "id": "578:8",
      "name": "Money",
      "sourceName": "Filled/Money",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money--filled--578-8.svg"
    },
    {
      "id": "589:20",
      "name": "Two-wheeler",
      "sourceName": "Filled/Two-wheeler",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/two-wheeler--filled--589-20.svg"
    },
    {
      "id": "596:30",
      "name": "Money-4",
      "sourceName": "Filled/Money-4",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money-4--filled--596-30.svg"
    },
    {
      "id": "596:36",
      "name": "Money-5",
      "sourceName": "Filled/Money-5",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money-5--filled--596-36.svg"
    },
    {
      "id": "642:10",
      "name": "Money-6",
      "sourceName": "Filled/Money-6",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money-6--filled--642-10.svg"
    },
    {
      "id": "679:28",
      "name": "Calculate",
      "sourceName": "Filled/Calculate",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/calculate--filled--679-28.svg"
    },
    {
      "id": "679:86",
      "name": "Document -2",
      "sourceName": "Filled/Document -2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/document-2--filled--679-86.svg"
    },
    {
      "id": "679:95",
      "name": "Lock-in",
      "sourceName": "Filled/Lock-in",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/lock-in--filled--679-95.png"
    },
    {
      "id": "679:100",
      "name": "Withdrawal",
      "sourceName": "Filled/Withdrawal",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/withdrawal--filled--679-100.svg"
    },
    {
      "id": "679:105",
      "name": "FAQs",
      "sourceName": "Filled/FAQs",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/faqs--filled--679-105.svg"
    },
    {
      "id": "679:176",
      "name": "Calculator",
      "sourceName": "Filled/Calculator",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/calculator--filled--679-176.svg"
    },
    {
      "id": "679:182",
      "name": "Add person",
      "sourceName": "Filled/Add person",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/add-person--filled--679-182.svg"
    },
    {
      "id": "679:203",
      "name": "Chequebook",
      "sourceName": "Filled/Chequebook",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/chequebook--filled--679-203.svg"
    },
    {
      "id": "679:233",
      "name": "Progress steps",
      "sourceName": "Filled/Progress steps",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/progress-steps--filled--679-233.svg"
    },
    {
      "id": "679:239",
      "name": "Chevron down",
      "sourceName": "Filled/Chevron down",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/chevron-down--filled--679-239.svg"
    },
    {
      "id": "717:260",
      "name": "Chevron up",
      "sourceName": "Filled/Chevron up",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/chevron-up--filled--717-260.svg"
    },
    {
      "id": "679:253",
      "name": "Mandate",
      "sourceName": "Filled/Mandate",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/mandate--filled--679-253.svg"
    },
    {
      "id": "698:18",
      "name": "Settings",
      "sourceName": "Filled/Settings",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/settings--filled--698-18.svg"
    },
    {
      "id": "768:564",
      "name": "Money-7",
      "sourceName": "Filled/Money-7",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money-7--filled--768-564.svg"
    },
    {
      "id": "788:18",
      "name": "Graduation",
      "sourceName": "Filled/Graduation",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/graduation--filled--788-18.svg"
    },
    {
      "id": "792:17",
      "name": "Minimum-arrows",
      "sourceName": "Filled/Minimum-arrows",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/minimum-arrows--filled--792-17.svg"
    },
    {
      "id": "792:34",
      "name": "Hand-check",
      "sourceName": "Filled/Hand-check",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/hand-check--filled--792-34.svg"
    },
    {
      "id": "878:27",
      "name": "Hand-gift",
      "sourceName": "Filled/Hand-gift",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/hand-gift--filled--878-27.svg"
    },
    {
      "id": "878:39",
      "name": "bank-active",
      "sourceName": "Filled/bank-active",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/bank-active--filled--878-39.svg"
    },
    {
      "id": "881:12",
      "name": "Identity",
      "sourceName": "Filled/Identity",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/identity--filled--881-12.svg"
    },
    {
      "id": "883:22",
      "name": "renew",
      "sourceName": "Filled/renew",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/renew--filled--883-22.svg"
    },
    {
      "id": "885:14",
      "name": "Verified",
      "sourceName": "Filled/Verified",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/verified--filled--885-14.png"
    },
    {
      "id": "887:18",
      "name": "play",
      "sourceName": "Filled/play",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/play--filled--887-18.svg"
    },
    {
      "id": "929:18",
      "name": "Delete",
      "sourceName": "Filled/Delete",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/delete--filled--929-18.svg"
    },
    {
      "id": "950:29",
      "name": "up-trend",
      "sourceName": "Filled/up-trend",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/up-trend--filled--950-29.svg"
    },
    {
      "id": "950:71",
      "name": "calendar-money",
      "sourceName": "Filled/calendar-money",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/calendar-money--filled--950-71.svg"
    },
    {
      "id": "1060:13",
      "name": "Money-8",
      "sourceName": "Filled/Money-8",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/money-8--filled--1060-13.svg"
    },
    {
      "id": "1060:21",
      "name": "Graph-2",
      "sourceName": "Filled/Graph-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/graph-2--filled--1060-21.svg"
    },
    {
      "id": "1062:29",
      "name": "Document check",
      "sourceName": "Filled/Document check",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/document-check--filled--1062-29.svg"
    },
    {
      "id": "1063:42",
      "name": "Apply",
      "sourceName": "Filled/Apply",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/apply--filled--1063-42.svg"
    },
    {
      "id": "1064:50",
      "name": "card-shield",
      "sourceName": "Filled/card-shield",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/card-shield--filled--1064-50.svg"
    },
    {
      "id": "1068:13",
      "name": "View",
      "sourceName": "Filled/View",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/view--filled--1068-13.svg"
    },
    {
      "id": "1069:1247",
      "name": "Girl-child",
      "sourceName": "Filled/Girl-child",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/girl-child--filled--1069-1247.svg"
    },
    {
      "id": "1098:18",
      "name": "Deliverable",
      "sourceName": "Filled/Deliverable",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/deliverable--filled--1098-18.svg"
    },
    {
      "id": "1106:13",
      "name": "Disability",
      "sourceName": "Filled/Disability",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/disability--filled--1106-13.svg"
    },
    {
      "id": "1107:28",
      "name": "Time",
      "sourceName": "Filled/Time",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/time--filled--1107-28.svg"
    },
    {
      "id": "1107:35",
      "name": "Mobile",
      "sourceName": "Filled/Mobile",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/mobile--filled--1107-35.svg"
    },
    {
      "id": "1109:44",
      "name": "Illness",
      "sourceName": "Filled/Illness",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/illness--filled--1109-44.svg"
    },
    {
      "id": "1130:18",
      "name": "Mobile",
      "sourceName": "Filled/Mobile",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/mobile--filled--1130-18.svg"
    },
    {
      "id": "1165:14",
      "name": "Bank-2",
      "sourceName": "Filled/Bank-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/bank-2--filled--1165-14.svg"
    },
    {
      "id": "1165:19",
      "name": "Windows",
      "sourceName": "Filled/Windows",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/windows--filled--1165-19.svg"
    },
    {
      "id": "1169:27",
      "name": "Senior-citizen",
      "sourceName": "Filled/Senior-citizen",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/senior-citizen--filled--1169-27.png"
    },
    {
      "id": "1185:20",
      "name": "Senior-citizen-2",
      "sourceName": "Filled/Senior-citizen-2",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/senior-citizen-2--filled--1185-20.svg"
    },
    {
      "id": "1195:13",
      "name": "Bookmark",
      "sourceName": "Filled/Bookmark",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/bookmark--filled--1195-13.svg"
    },
    {
      "id": "1196:6",
      "name": "Menu",
      "sourceName": "Filled/Menu",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/menu--filled--1196-6.svg"
    },
    {
      "id": "1224:30",
      "name": "Government",
      "sourceName": "Filled/Government",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/government--filled--1224-30.svg"
    },
    {
      "id": "1257:12",
      "name": "Email",
      "sourceName": "Filled/Email",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/general/filled/email--filled--1257-12.png"
    },
    {
      "id": "1257:34",
      "name": "Location",
      "sourceName": "Filled/Location",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/location--filled--1257-34.svg"
    },
    {
      "id": "1295:7",
      "name": "Hospital",
      "sourceName": "Filled/Hospital",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/hospital--filled--1295-7.svg"
    },
    {
      "id": "1365:21",
      "name": "Tax exemption",
      "sourceName": "Filled/Tax exemption",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/tax-exemption--filled--1365-21.svg"
    },
    {
      "id": "1365:30",
      "name": "Graph-3",
      "sourceName": "Filled/Graph-3",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/graph-3--filled--1365-30.svg"
    },
    {
      "id": "1365:35",
      "name": "Exchange",
      "sourceName": "Filled/Exchange",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/exchange--filled--1365-35.svg"
    },
    {
      "id": "1442:16",
      "name": "Visibility On",
      "sourceName": "Filled/Visibility On",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/visibility-on--filled--1442-16.svg"
    },
    {
      "id": "1442:15",
      "name": "Visibility Off",
      "sourceName": "Filled/Visibility Off",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/visibility-off--filled--1442-15.svg"
    },
    {
      "id": "1500:7",
      "name": "Live",
      "sourceName": "Filled/Live",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/live--filled--1500-7.svg"
    },
    {
      "id": "1576:13",
      "name": "Drip",
      "sourceName": "Filled/Drip",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/drip--filled--1576-13.svg"
    },
    {
      "id": "1576:21",
      "name": "Renew",
      "sourceName": "Filled/Renew",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/renew--filled--1576-21.svg"
    },
    {
      "id": "1576:48",
      "name": "Donor",
      "sourceName": "Filled/Donor",
      "category": "general",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/filled/donor--filled--1576-48.svg"
    },
    {
      "id": "235:115",
      "name": "Chevron right",
      "sourceName": "Line/Chevron right",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/chevron-right--line--235-115.svg"
    },
    {
      "id": "235:116",
      "name": "Chevron left",
      "sourceName": "Line/Chevron left",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/chevron-left--line--235-116.svg"
    },
    {
      "id": "235:117",
      "name": "Chevron up",
      "sourceName": "Line/Chevron up",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/chevron-up--line--235-117.svg"
    },
    {
      "id": "235:118",
      "name": "Chevron down",
      "sourceName": "Line/Chevron down",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/chevron-down--line--235-118.svg"
    },
    {
      "id": "235:119",
      "name": "External",
      "sourceName": "Line/External",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/external--line--235-119.svg"
    },
    {
      "id": "235:120",
      "name": "Expand",
      "sourceName": "Line/Expand",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/expand--line--235-120.svg"
    },
    {
      "id": "237:430",
      "name": "Arrow-out",
      "sourceName": "Line/Arrow-out",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/arrow-out--line--237-430.svg"
    },
    {
      "id": "237:431",
      "name": "Arrow-in",
      "sourceName": "Line/Arrow-in",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/arrow-in--line--237-431.svg"
    },
    {
      "id": "237:432",
      "name": "Repeat",
      "sourceName": "Line/Repeat",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/repeat--line--237-432.svg"
    },
    {
      "id": "237:433",
      "name": "Share",
      "sourceName": "Line/Share",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/share--line--237-433.svg"
    },
    {
      "id": "237:434",
      "name": "Close",
      "sourceName": "Line/Close",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/close--line--237-434.svg"
    },
    {
      "id": "237:435",
      "name": "Copy",
      "sourceName": "Line/Copy",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/copy--line--237-435.svg"
    },
    {
      "id": "237:436",
      "name": "Tick",
      "sourceName": "Line/Tick",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/tick--line--237-436.svg"
    },
    {
      "id": "237:563",
      "name": "Glitter-2",
      "sourceName": "Line/Glitter-2",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/glitter-2--line--237-563.svg"
    },
    {
      "id": "244:27",
      "name": "Link",
      "sourceName": "Line/Link",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/link--line--244-27.svg"
    },
    {
      "id": "428:13",
      "name": "Notify",
      "sourceName": "Line/Notify",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/notify--line--428-13.svg"
    },
    {
      "id": "519:31",
      "name": "Empty",
      "sourceName": "Line/Empty",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/empty--line--519-31.svg"
    },
    {
      "id": "519:38",
      "name": "Add",
      "sourceName": "Line/Add",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/add--line--519-38.svg"
    },
    {
      "id": "549:256",
      "name": "Time",
      "sourceName": "Line/Time",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/time--line--549-256.svg"
    },
    {
      "id": "555:310",
      "name": "Information",
      "sourceName": "Line/Information",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/information--line--555-310.svg"
    },
    {
      "id": "599:44",
      "name": "Download",
      "sourceName": "Line/Download",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/download--line--599-44.svg"
    },
    {
      "id": "650:32",
      "name": "Transactions",
      "sourceName": "Line/Transactions",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/transactions--line--650-32.svg"
    },
    {
      "id": "679:220",
      "name": "Add-2",
      "sourceName": "Line/Add-2",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/add-2--line--679-220.svg"
    },
    {
      "id": "1061:24",
      "name": "Speed",
      "sourceName": "Line/Speed",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/speed--line--1061-24.svg"
    },
    {
      "id": "1069:51",
      "name": "search",
      "sourceName": "Line/search",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/search--line--1069-51.svg"
    },
    {
      "id": "1117:13",
      "name": "date and number",
      "sourceName": "Line/date and number",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/date-and-number--line--1117-13.svg"
    },
    {
      "id": "1117:16",
      "name": "password",
      "sourceName": "Line/password",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/password--line--1117-16.svg"
    },
    {
      "id": "1130:14",
      "name": "QR code",
      "sourceName": "Line/QR code",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/qr-code--line--1130-14.svg"
    },
    {
      "id": "1226:13",
      "name": "up-trend",
      "sourceName": "Line/up-trend",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/up-trend--line--1226-13.svg"
    },
    {
      "id": "1594:14",
      "name": "piechart",
      "sourceName": "Line/piechart",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/piechart--line--1594-14.svg"
    },
    {
      "id": "1622:7",
      "name": "piechart-2",
      "sourceName": "Line/piechart-2",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/piechart-2--line--1622-7.svg"
    },
    {
      "id": "1733:6",
      "name": "Refresh",
      "sourceName": "Line/Refresh",
      "category": "general",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/general/line/refresh--line--1733-6.svg"
    },
    {
      "id": "235:377",
      "name": "SIP-Mutual funds",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/sip-mutual-funds--line--235-377.svg"
    },
    {
      "id": "235:379",
      "name": "SIP-Mutual funds",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/sip-mutual-funds--filled--235-379.svg"
    },
    {
      "id": "235:382",
      "name": "Stocks and IPO",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/stocks-and-ipo--line--235-382.svg"
    },
    {
      "id": "235:384",
      "name": "Stocks and IPO",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/stocks-and-ipo--filled--235-384.svg"
    },
    {
      "id": "1232:54",
      "name": "Demat & trading",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/demat-and-trading--filled--1232-54.svg"
    },
    {
      "id": "235:387",
      "name": "Government schemes",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/government-schemes--line--235-387.svg"
    },
    {
      "id": "235:389",
      "name": "Government schemes",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/government-schemes--filled--235-389.svg"
    },
    {
      "id": "235:392",
      "name": "Tax solutions",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/tax-solutions--line--235-392.svg"
    },
    {
      "id": "235:394",
      "name": "Tax solutions",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/tax-solutions--filled--235-394.svg"
    },
    {
      "id": "235:402",
      "name": "Life insurance",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/life-insurance--line--235-402.svg"
    },
    {
      "id": "235:404",
      "name": "Life insurance",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/life-insurance--filled--235-404.svg"
    },
    {
      "id": "1443:76",
      "name": "Health insurance",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/health-insurance--line--1443-76.svg"
    },
    {
      "id": "1443:80",
      "name": "Health insurance",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/health-insurance--filled--1443-80.svg"
    },
    {
      "id": "235:407",
      "name": "Travel insurance",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/travel-insurance--line--235-407.svg"
    },
    {
      "id": "235:409",
      "name": "Travel insurance",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/travel-insurance--filled--235-409.svg"
    },
    {
      "id": "235:412",
      "name": "Vehicle insurance",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/vehicle-insurance--line--235-412.svg"
    },
    {
      "id": "235:414",
      "name": "Vehicle insurance",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/vehicle-insurance--filled--235-414.svg"
    },
    {
      "id": "235:417",
      "name": "Guaranteed income plan",
      "sourceName": "Guaranteed income plan",
      "category": "product",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/special/guaranteed-income-plan--special--235-417.svg"
    },
    {
      "id": "235:478",
      "name": "Term life",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/term-life--line--235-478.svg"
    },
    {
      "id": "235:479",
      "name": "Term life",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/filled/term-life--filled--235-479.png"
    },
    {
      "id": "235:515",
      "name": "Term life",
      "sourceName": "Type=Special",
      "category": "product",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/special/term-life--special--235-515.svg"
    },
    {
      "id": "235:511",
      "name": "Cancer cover",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/cancer-cover--line--235-511.svg"
    },
    {
      "id": "235:500",
      "name": "Cancer cover",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/cancer-cover--filled--235-500.svg"
    },
    {
      "id": "235:502",
      "name": "Cancer cover",
      "sourceName": "Type=Special",
      "category": "product",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/special/cancer-cover--special--235-502.svg"
    },
    {
      "id": "544:123",
      "name": "Health shield 360",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/health-shield-360--line--544-123.svg"
    },
    {
      "id": "237:41",
      "name": "Health shield 360",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/filled/health-shield-360--filled--237-41.png"
    },
    {
      "id": "237:42",
      "name": "Health shield 360",
      "sourceName": "Type=Special",
      "category": "product",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/special/health-shield-360--special--237-42.svg"
    },
    {
      "id": "544:101",
      "name": "Health shield 360 top up",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/health-shield-360-top-up--line--544-101.svg"
    },
    {
      "id": "237:88",
      "name": "Health shield 360 top up",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/filled/health-shield-360-top-up--filled--237-88.png"
    },
    {
      "id": "237:89",
      "name": "Health shield 360 top up",
      "sourceName": "Type=Special",
      "category": "product",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/special/health-shield-360-top-up--special--237-89.svg"
    },
    {
      "id": "547:167",
      "name": "PMJJBY",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/pmjjby--line--547-167.svg"
    },
    {
      "id": "547:170",
      "name": "PMJJBY",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/pmjjby--filled--547-170.svg"
    },
    {
      "id": "547:164",
      "name": "PMJJBY",
      "sourceName": "Type=Special",
      "category": "product",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/special/pmjjby--special--547-164.svg"
    },
    {
      "id": "547:228",
      "name": "PMSBY",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/pmsby--line--547-228.svg"
    },
    {
      "id": "547:232",
      "name": "PMSBY",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/pmsby--filled--547-232.svg"
    },
    {
      "id": "547:212",
      "name": "PMSBY",
      "sourceName": "Type=Special",
      "category": "product",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/special/pmsby--special--547-212.png"
    },
    {
      "id": "319:18",
      "name": "Loans",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/loans--line--319-18.svg"
    },
    {
      "id": "319:20",
      "name": "Loans",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/loans--filled--319-20.svg"
    },
    {
      "id": "355:262",
      "name": "Home loan",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/home-loan--line--355-262.svg"
    },
    {
      "id": "355:264",
      "name": "Home loan",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/home-loan--filled--355-264.svg"
    },
    {
      "id": "324:167",
      "name": "Auto loan",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/auto-loan--line--324-167.svg"
    },
    {
      "id": "324:169",
      "name": "Auto loan",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/auto-loan--filled--324-169.svg"
    },
    {
      "id": "483:16",
      "name": "Auto loan",
      "sourceName": "Special",
      "category": "product",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/special/auto-loan--special--483-16.png"
    },
    {
      "id": "530:283",
      "name": "Two wheeler loan",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/two-wheeler-loan--line--530-283.svg"
    },
    {
      "id": "324:207",
      "name": "Two wheeler loan",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/two-wheeler-loan--filled--324-207.svg"
    },
    {
      "id": "530:321",
      "name": "Education loan",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/education-loan--line--530-321.svg"
    },
    {
      "id": "530:326",
      "name": "Education loan",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/education-loan--filled--530-326.svg"
    },
    {
      "id": "530:337",
      "name": "Personal loan",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/personal-loan--line--530-337.svg"
    },
    {
      "id": "530:342",
      "name": "Personal loan",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/personal-loan--filled--530-342.svg"
    },
    {
      "id": "530:353",
      "name": "Gold loan",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/line/gold-loan--line--530-353.png"
    },
    {
      "id": "530:358",
      "name": "Gold loan",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/gold-loan--filled--530-358.svg"
    },
    {
      "id": "679:80",
      "name": "PPF",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/ppf--line--679-80.svg"
    },
    {
      "id": "679:39",
      "name": "PPF",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/ppf--filled--679-39.svg"
    },
    {
      "id": "761:129",
      "name": "PPF",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 22,
      "height": 22,
      "format": "svg",
      "asset": "assets/icons/product/line/ppf--line--761-129.svg"
    },
    {
      "id": "761:134",
      "name": "PPF",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 22,
      "height": 22,
      "format": "svg",
      "asset": "assets/icons/product/filled/ppf--filled--761-134.svg"
    },
    {
      "id": "878:54",
      "name": "Flexicash",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/flexicash--line--878-54.svg"
    },
    {
      "id": "878:59",
      "name": "Flexicash",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/flexicash--filled--878-59.svg"
    },
    {
      "id": "888:21",
      "name": "Close-flexicash",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/close-flexicash--line--888-21.svg"
    },
    {
      "id": "888:25",
      "name": "Close-flexicash",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/close-flexicash--filled--888-25.svg"
    },
    {
      "id": "1419:53",
      "name": "SCSS",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/scss--line--1419-53.svg"
    },
    {
      "id": "931:406",
      "name": "SCSS",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/scss--filled--931-406.svg"
    },
    {
      "id": "934:464",
      "name": "NPS",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/nps--filled--934-464.svg"
    },
    {
      "id": "1069:19",
      "name": "SSY",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/filled/ssy--filled--1069-19.png"
    },
    {
      "id": "1168:12",
      "name": "APY",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/filled/apy--filled--1168-12.png"
    },
    {
      "id": "1643:15",
      "name": "PMJJBY",
      "sourceName": "Type=FIlled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/filled/pmjjby--filled--1643-15.png"
    },
    {
      "id": "1422:66",
      "name": "FRSB",
      "sourceName": "Type=Line",
      "category": "product",
      "variant": "line",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/line/frsb--line--1422-66.svg"
    },
    {
      "id": "1199:44",
      "name": "FRSB",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/frsb--filled--1199-44.svg"
    },
    {
      "id": "1069:11",
      "name": "Property-loan",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/property-loan--filled--1069-11.svg"
    },
    {
      "id": "1084:9",
      "name": "Pre-approved card",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/product/filled/pre-approved-card--filled--1084-9.png"
    },
    {
      "id": "1364:25",
      "name": "SGB",
      "sourceName": "Type=Filled",
      "category": "product",
      "variant": "filled",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/product/filled/sgb--filled--1364-25.svg"
    },
    {
      "id": "239:49",
      "name": "Graph",
      "sourceName": "Graph",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/graph--special--239-49.svg"
    },
    {
      "id": "239:51",
      "name": "Document-1",
      "sourceName": "Document-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/document-1--special--239-51.svg"
    },
    {
      "id": "239:52",
      "name": "Calculator",
      "sourceName": "Calculator",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/calculator--special--239-52.svg"
    },
    {
      "id": "522:98",
      "name": "Money-1",
      "sourceName": "Money-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/money-1--special--522-98.png"
    },
    {
      "id": "522:116",
      "name": "Family",
      "sourceName": "Family",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/family--special--522-116.svg"
    },
    {
      "id": "522:125",
      "name": "Invest",
      "sourceName": "Invest",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/invest--special--522-125.svg"
    },
    {
      "id": "522:138",
      "name": "Returns",
      "sourceName": "Returns",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/returns--special--522-138.png"
    },
    {
      "id": "524:178",
      "name": "Helmet",
      "sourceName": "Helmet",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/helmet--special--524-178.png"
    },
    {
      "id": "524:184",
      "name": "Electrical",
      "sourceName": "Electrical",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/electrical--special--524-184.svg"
    },
    {
      "id": "524:204",
      "name": "Calendar",
      "sourceName": "Calendar",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/calendar--special--524-204.svg"
    },
    {
      "id": "524:209",
      "name": "Car repair",
      "sourceName": "Car repair",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/car-repair--special--524-209.svg"
    },
    {
      "id": "527:52",
      "name": "Chart-1",
      "sourceName": "Chart-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/chart-1--special--527-52.svg"
    },
    {
      "id": "527:57",
      "name": "cash-payment-1",
      "sourceName": "cash-payment-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/cash-payment-1--special--527-57.svg"
    },
    {
      "id": "527:62",
      "name": "contact-1",
      "sourceName": "contact-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/contact-1--special--527-62.svg"
    },
    {
      "id": "527:95",
      "name": "tax-1",
      "sourceName": "tax-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/tax-1--special--527-95.png"
    },
    {
      "id": "527:127",
      "name": "location",
      "sourceName": "location",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/location--special--527-127.png"
    },
    {
      "id": "527:142",
      "name": "expense 1",
      "sourceName": "expense 1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/expense-1--special--527-142.png"
    },
    {
      "id": "527:147",
      "name": "agreement-1",
      "sourceName": "agreement-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/agreement-1--special--527-147.svg"
    },
    {
      "id": "527:188",
      "name": "refinance 1",
      "sourceName": "refinance 1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/refinance-1--special--527-188.png"
    },
    {
      "id": "527:194",
      "name": "location",
      "sourceName": "location",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/location--special--527-194.svg"
    },
    {
      "id": "527:206",
      "name": "tax-2",
      "sourceName": "tax-2",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/tax-2--special--527-206.svg"
    },
    {
      "id": "527:213",
      "name": "letter-1",
      "sourceName": "letter-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/letter-1--special--527-213.svg"
    },
    {
      "id": "527:277",
      "name": "writing-1",
      "sourceName": "writing-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/writing-1--special--527-277.png"
    },
    {
      "id": "527:276",
      "name": "writing-2",
      "sourceName": "writing-2",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/writing-2--special--527-276.svg"
    },
    {
      "id": "527:275",
      "name": "signature-1",
      "sourceName": "signature-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/signature-1--special--527-275.svg"
    },
    {
      "id": "527:274",
      "name": "letter-1",
      "sourceName": "letter-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/letter-1--special--527-274.svg"
    },
    {
      "id": "527:273",
      "name": "calendar-2",
      "sourceName": "calendar-2",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/calendar-2--special--527-273.svg"
    },
    {
      "id": "527:272",
      "name": "letter-2",
      "sourceName": "letter-2",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/letter-2--special--527-272.svg"
    },
    {
      "id": "642:21",
      "name": "stamp-1",
      "sourceName": "stamp-1",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/stamp-1--special--642-21.svg"
    },
    {
      "id": "658:5",
      "name": "crane",
      "sourceName": "crane",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/crane--special--658-5.svg"
    },
    {
      "id": "658:11",
      "name": "cashless",
      "sourceName": "cashless",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/cashless--special--658-11.svg"
    },
    {
      "id": "659:39",
      "name": "Car safety",
      "sourceName": "Car safety",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/car-safety--special--659-39.svg"
    },
    {
      "id": "679:166",
      "name": "Lock",
      "sourceName": "Lock",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/lock--special--679-166.png"
    },
    {
      "id": "679:167",
      "name": "Moneybag",
      "sourceName": "Moneybag",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/moneybag--special--679-167.svg"
    },
    {
      "id": "679:168",
      "name": "Withdrawals",
      "sourceName": "Withdrawals",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/withdrawals--special--679-168.svg"
    },
    {
      "id": "679:169",
      "name": "Money-2",
      "sourceName": "Money-2",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/money-2--special--679-169.svg"
    },
    {
      "id": "711:10",
      "name": "chart-3",
      "sourceName": "chart-3",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/chart-3--special--711-10.svg"
    },
    {
      "id": "711:33",
      "name": "document-reset",
      "sourceName": "document-reset",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/document-reset--special--711-33.png"
    },
    {
      "id": "715:46",
      "name": "document-interest",
      "sourceName": "document-interest",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/document-interest--special--715-46.svg"
    },
    {
      "id": "1061:19",
      "name": "Money-shield",
      "sourceName": "Money-shield",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/money-shield--special--1061-19.png"
    },
    {
      "id": "1099:70",
      "name": "Block-credit-card",
      "sourceName": "Block-credit-card",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/block-credit-card--special--1099-70.svg"
    },
    {
      "id": "1099:69",
      "name": "Block-debit-card",
      "sourceName": "Block-debit-card",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/block-debit-card--special--1099-69.svg"
    },
    {
      "id": "1099:68",
      "name": "Cheque",
      "sourceName": "Cheque",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/cheque--special--1099-68.svg"
    },
    {
      "id": "1100:111",
      "name": "Stop-cheque",
      "sourceName": "Stop-cheque",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/stop-cheque--special--1100-111.svg"
    },
    {
      "id": "1100:138",
      "name": "Card-PIN",
      "sourceName": "Card-PIN",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/card-pin--special--1100-138.svg"
    },
    {
      "id": "1100:166",
      "name": "Positive-pay",
      "sourceName": "Positive-pay",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "png",
      "asset": "assets/icons/special/special/positive-pay--special--1100-166.png"
    },
    {
      "id": "1222:25",
      "name": "tax-free",
      "sourceName": "tax-free",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/tax-free--special--1222-25.svg"
    },
    {
      "id": "1516:7",
      "name": "Healthcare",
      "sourceName": "Healthcare",
      "category": "special",
      "variant": "special",
      "width": 24,
      "height": 24,
      "format": "svg",
      "asset": "assets/icons/special/special/healthcare--special--1516-7.svg"
    },
    {
      "id": "1614:10",
      "name": "Call history",
      "sourceName": "Call history",
      "category": "special",
      "variant": "special",
      "width": 20,
      "height": 20,
      "format": "svg",
      "asset": "assets/icons/special/special/call-history--special--1614-10.svg"
    },
    {
      "id": "1614:15",
      "name": "no document",
      "sourceName": "no document",
      "category": "special",
      "variant": "special",
      "width": 20,
      "height": 20,
      "format": "svg",
      "asset": "assets/icons/special/special/no-document--special--1614-15.svg"
    },
    {
      "id": "1614:20",
      "name": "shield document",
      "sourceName": "shield document",
      "category": "special",
      "variant": "special",
      "width": 20,
      "height": 20,
      "format": "svg",
      "asset": "assets/icons/special/special/shield-document--special--1614-20.svg"
    },
    {
      "id": "370:173",
      "name": "Home",
      "sourceName": "Home/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/home--outlined--370-173.svg"
    },
    {
      "id": "370:174",
      "name": "Home",
      "sourceName": "Home/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/home--filled--370-174.svg"
    },
    {
      "id": "370:178",
      "name": "Payments",
      "sourceName": "Payments/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/payments--outlined--370-178.svg"
    },
    {
      "id": "370:169",
      "name": "Payments",
      "sourceName": "Payments/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/payments--filled--370-169.svg"
    },
    {
      "id": "370:172",
      "name": "Accounts",
      "sourceName": "Accounts/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/accounts--outlined--370-172.svg"
    },
    {
      "id": "370:165",
      "name": "Accounts",
      "sourceName": "Accounts/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/accounts--filled--370-165.svg"
    },
    {
      "id": "370:163",
      "name": "Deposits",
      "sourceName": "Deposits/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/deposits--outlined--370-163.svg"
    },
    {
      "id": "370:164",
      "name": "Deposits",
      "sourceName": "Deposits/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/deposits--filled--370-164.svg"
    },
    {
      "id": "370:166",
      "name": "Investments",
      "sourceName": "Investments/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/investments--outlined--370-166.svg"
    },
    {
      "id": "370:177",
      "name": "Investments",
      "sourceName": "Investments/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/investments--filled--370-177.svg"
    },
    {
      "id": "370:175",
      "name": "Insurance",
      "sourceName": "Insurance/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/insurance--outlined--370-175.svg"
    },
    {
      "id": "370:168",
      "name": "Insurance",
      "sourceName": "Insurance/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/insurance--filled--370-168.svg"
    },
    {
      "id": "370:167",
      "name": "Loans",
      "sourceName": "Loans/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/loans--outlined--370-167.svg"
    },
    {
      "id": "370:171",
      "name": "Loans",
      "sourceName": "Loans/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/loans--filled--370-171.svg"
    },
    {
      "id": "370:162",
      "name": "Cards",
      "sourceName": "Cards/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/cards--outlined--370-162.svg"
    },
    {
      "id": "370:176",
      "name": "Cards",
      "sourceName": "Cards/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/cards--filled--370-176.svg"
    },
    {
      "id": "370:170",
      "name": "Service",
      "sourceName": "Service/Outlined",
      "category": "sideNav",
      "variant": "outlined",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/outlined/service--outlined--370-170.svg"
    },
    {
      "id": "370:161",
      "name": "Service",
      "sourceName": "Service/Filled",
      "category": "sideNav",
      "variant": "filled",
      "width": 16,
      "height": 16,
      "format": "svg",
      "asset": "assets/icons/side-nav/filled/service--filled--370-161.svg"
    }
  ]
};
