import 'dart:ui' show FontFeature;
import 'package:flutter/material.dart';

/// ICICI Global DS tokens — generated by ICICI Global DS v0.1.0
/// Source of truth: icici-global-ds/js/tokens.js
/// Regenerate from the DesignOS Developers page; do not edit by hand.

class DsColors {
  DsColors._();

  // Brand colours
  static const Color brandOrange = Color(0xFFE3530F);
  static const Color brandMaroon = Color(0xFFBE2A2A);

  // Primary orange
  static const Color primaryOrange80 = Color(0xFFF4B094);
  static const Color primaryOrange90 = Color(0xFFE8692E);
  static const Color primaryOrange100 = Color(0xFFD44500);
  static const Color primaryOrange110 = Color(0xFFA93600);
  static const Color primaryOrange120 = Color(0xFF732500);

  // Primary maroon
  static const Color primaryMaroon80 = Color(0xFFDA7B80);
  static const Color primaryMaroon90 = Color(0xFFBC343A);
  static const Color primaryMaroon100 = Color(0xFF94292E);
  static const Color primaryMaroon110 = Color(0xFF6C1E21);
  static const Color primaryMaroon120 = Color(0xFF441315);

  // Absolute neutrals
  static const Color neutralBaseBlack = Color(0xFF000000);
  static const Color neutralBaseWhite = Color(0xFFFFFFFF);

  // Neutral grey
  static const Color neutralGrey60 = Color(0xFFF7F7F7);
  static const Color neutralGrey70 = Color(0xFFE7E8E9);
  static const Color neutralGrey80 = Color(0xFFCDCFD0);
  static const Color neutralGrey90 = Color(0xFFB2B5B8);
  static const Color neutralGrey100 = Color(0xFF979B9F);
  static const Color neutralGrey110 = Color(0xFF7D8287);
  static const Color neutralGrey120 = Color(0xFF64696D);
  static const Color neutralGrey130 = Color(0xFF4C4F52);
  static const Color neutralGrey140 = Color(0xFF333638);
  static const Color neutralGrey150 = Color(0xFF202428);

  // Surface cool grey
  static const Color surfaceCoolGrey90 = Color(0xFFFCFCFD);
  static const Color surfaceCoolGrey100 = Color(0xFFF8F9FB);
  static const Color surfaceCoolGrey110 = Color(0xFFEFF1F6);

  // Success green
  static const Color success50 = Color(0xFFECFDF3);
  static const Color success100 = Color(0xFFD1FADF);
  static const Color success500 = Color(0xFF12B76A);
  static const Color success600 = Color(0xFF039855);
  static const Color success700 = Color(0xFF027A48);

  // Error red
  static const Color error50 = Color(0xFFFEF3F2);
  static const Color error100 = Color(0xFFFEE4E2);
  static const Color error500 = Color(0xFFF04438);
  static const Color error600 = Color(0xFFD92D20);
  static const Color error700 = Color(0xFFB42318);

  // Warning amber
  static const Color warning50 = Color(0xFFFFFAEB);
  static const Color warning100 = Color(0xFFFEF0C7);
  static const Color warning500 = Color(0xFFF79009);
  static const Color warning600 = Color(0xFFDC6803);
  static const Color warning700 = Color(0xFFB54708);

  // Info blue
  static const Color info50 = Color(0xFFEFF8FF);
  static const Color info100 = Color(0xFFD1E9FF);
  static const Color info500 = Color(0xFF2E90FA);
  static const Color info600 = Color(0xFF1570EF);
  static const Color info700 = Color(0xFF175CD3);

  // Hero gradient — login hero, account card, section covers
  static const Gradient hero = LinearGradient(
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
    colors: [Color(0xFFE3530F), Color(0xFFBE2A2A)],
  );

  // Primary button fill — base + 12% white gradient overlay
  static const Color buttonPrimaryFillBase = primaryOrange100;
  static const Gradient buttonPrimaryFill = LinearGradient(
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
    colors: [Color(0x1FFFFFFF), Color(0x00FFFFFF)],
  );

  // Button stroke gradient — visible peach-to-orange shell
  static const double buttonStrokeWidth = 1;
  static const Gradient buttonStroke = LinearGradient(
    begin: Alignment.topCenter,
    end: Alignment.bottomCenter,
    colors: [Color(0xFFF4B094), Color(0xFFE8692E), Color(0xFFD44500)],
    stops: [0, .45, 1],
  );
}

class DsSpacing {
  DsSpacing._();

  static const double xxs = 2; // Hairline gaps
  static const double xs = 4; // Icon-to-label gaps
  static const double sm = 8; // Inside compact components
  static const double md = 12; // Between related elements
  static const double lg = 16; // Screen margins (mobile), card padding
  static const double xl = 20; // Comfortable card padding
  static const double xl2 = 24; // Between sections
  static const double xl3 = 32; // Large section breaks
  static const double xl4 = 40; // Page-level separation
  static const double xl5 = 48; // Hero padding
  static const double xl6 = 64; // Web page headers
}

class DsRadius {
  DsRadius._();

  static const double xs = 4; // Tags, tiny elements
  static const double sm = 8; // Small controls, segments
  static const double md = 12; // Buttons, inputs, OTP boxes
  static const double lg = 16; // Cards, alerts
  static const double xl = 24; // Sheets, page headers
  static const double full = 999; // Pills, badges, avatars
}

class DsText {
  DsText._();

  static const String fontFamily = 'Mulish';

  static const TextStyle displayLarge = TextStyle(
    fontFamily: fontFamily,
    fontSize: 32,
    height: 1.25,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle displayMedium = TextStyle(
    fontFamily: fontFamily,
    fontSize: 28,
    height: 1.29,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle displaySmall = TextStyle(
    fontFamily: fontFamily,
    fontSize: 24,
    height: 1.33,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle headingLargeBold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 20,
    height: 1.40,
    fontWeight: FontWeight.w700,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle headingLargeSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 20,
    height: 1.40,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle headingMediumBold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 16,
    height: 1.50,
    fontWeight: FontWeight.w700,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle headingMediumSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 16,
    height: 1.50,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle headingSmallBold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    height: 1.43,
    fontWeight: FontWeight.w700,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle headingSmallSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    height: 1.43,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle headingSmallRegular = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    height: 1.43,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle bodyLargeRegular = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    height: 1.43,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle bodyLargeSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    height: 1.43,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle bodyMediumRegular = TextStyle(
    fontFamily: fontFamily,
    fontSize: 13,
    height: 1.54,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle bodyMediumSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 13,
    height: 1.54,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle bodySmallRegular = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12,
    height: 1.33,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle bodySmallSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12,
    height: 1.33,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle captionRegular = TextStyle(
    fontFamily: fontFamily,
    fontSize: 11,
    height: 1.45,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle captionSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 11,
    height: 1.45,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle microSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 10,
    height: 1.40,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle inputLargeRegular = TextStyle(
    fontFamily: fontFamily,
    fontSize: 16,
    height: 1.50,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle inputLargeSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 16,
    height: 1.50,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle inputMediumRegular = TextStyle(
    fontFamily: fontFamily,
    fontSize: 13,
    height: 1.54,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle inputMediumSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 13,
    height: 1.54,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle buttonLarge = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    height: 1.14,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle buttonSmall = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12,
    height: 1.33,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle linkLarge = TextStyle(
    fontFamily: fontFamily,
    fontSize: 14,
    height: 1.43,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle linkSmall = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12,
    height: 1.33,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle labelBold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 11,
    height: 1.45,
    fontWeight: FontWeight.w700,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle labelSemibold = TextStyle(
    fontFamily: fontFamily,
    fontSize: 11,
    height: 1.45,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle navLevel1Default = TextStyle(
    fontFamily: fontFamily,
    fontSize: 13,
    height: 1.23,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle navLevel1Active = TextStyle(
    fontFamily: fontFamily,
    fontSize: 13,
    height: 1.23,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle navLevel2Default = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12,
    height: 1.33,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );

  static const TextStyle navLevel2Active = TextStyle(
    fontFamily: fontFamily,
    fontSize: 12,
    height: 1.33,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );
}
